Repository 05-gs-2109-wifight-the-power/star-app, pull requests merged in 2021-11, with the labels that each got.

#38 Test: Adding few more Tests
  client/components/Home.spec.js
  client/store/auth.spec.js
  package.json
  server/api/stars.spec.js
  server/api/users.spec.js
  server/db/models/Star.spec.js
  server/db/models/User.spec.js
Labels: Express, Sequelize, Tests, chai

#44 Navbar
  client/App.js
  client/Routes.js
  client/components/AuthForm.js
  client/components/Navbar.js
  client/components/SingleStarView.js
  client/components/Welcome.js
  client/store/auth.js
  public/index.html
  public/style.css
Labels: React

#49 Updating nav bar
  client/App.js
  client/Routes.js
  client/components/Navbar.js
  client/components/NotFound.js
  public/images/cart.png
  public/style.css
Labels: enhancement, React, CSS

#50 Task: Thank you for your purchase
  client/Routes.js
  client/components/ThankYou.js
  client/components/Welcome.js
Labels: React

#57 Fix: Cart Route & others'
  client/Routes.js
  client/components/AllStars.js
  client/components/Cart.js
  client/components/CartView.js
  client/store/shopping.js
  server/api/cart.js
  server/app.js
Labels: bug, enhancement, Express

#59 Update cart
  client/Routes.js
  client/components/Cart.js
  client/store/shopping.js
  script/seed.js
  server/api/cart.js
Labels: Express

#61 Fix: Updated Cart, fix bug
  client/components/Cart.js
  client/store/auth.js
  client/store/shopping.js
  server/api/cart.js
Labels: bug, Express, React

#62 Update cart
  client/Routes.js
  client/components/AllStars.js
  client/components/Cart.js
  client/store/auth.js
  client/store/shopping.js
  server/api/cart.js
  server/api/stars.js
Labels: bug, Express, React, Redux

#67 Fix: Readme
  README.md
Labels: documentation
